[tool.black]
# 行の最大の長さはPEP8準拠
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
# Blackと競合しないよう設定
profile = "black"
# 行の最大の長さはPEP8に準拠
line_length = 79
lines_after_imports = 2
force_single_line = 'True'
force_sort_within_sections = 'True'
order_by_type = 'False'
